"""
Text-to-Speech (TTS) module.

This area is responsible for generating and playing audio.

How it works:
1. Takes the final text response generated by the LLM.
2. Uses a TTS library (like gTTS) to convert the text into an audio file (e.g., mp3).
3. Uses an audio playback library (like pygame) to play the generated audio 
   directly to the user without requiring external media players.
"""

import os
from gtts import gTTS
import pygame

class VoiceSpeaker:
    """
    Handles converting text to speech and playing it back to the user out loud.
    """
    
    def __init__(self):
        """
        Initialize the Pygame mixer and ensure the temporary audio directory exists.
        """
        # Initialize the pygame mixer for audio playback
        pygame.mixer.init()
        
        # Ensure the temp_audio directory exists to save spoken responses
        self.temp_dir = "temp_audio"
        if not os.path.exists(self.temp_dir):
            os.makedirs(self.temp_dir)
            
    def speak(self, text: str):
        """
        Converts text to speech and plays it back audibly.
        
        Args:
            text (str): The text string to be spoken.
        """
        try:
            # Set the path for the temporary audio file
            audio_path = os.path.join(self.temp_dir, "response.mp3")
            
            # Generate the TTS audio
            tts = gTTS(text=text, lang='en')
            tts.save(audio_path)
            
            # Load and play the generated audio file
            pygame.mixer.music.load(audio_path)
            pygame.mixer.music.play()
            
            # Keep the script running while the audio plays out loud
            clock = pygame.time.Clock()
            while pygame.mixer.music.get_busy():
                clock.tick(10)
                
            # Unload the music so the file can be overwritten on the next turn
            # (Important for Windows to release the file lock)
            pygame.mixer.music.unload()
            
        except Exception as e:
            print(f"Audio playback error: {e}")

    def generate_audio_file(self, text: str) -> str:
        """
        Converts text to speech and saves it to a file.
        Returns the path to the saved audio file without playing it.
        """
        try:
            audio_path = os.path.join(self.temp_dir, "response.mp3")
            tts = gTTS(text=text, lang='en')
            tts.save(audio_path)
            return audio_path
        except Exception as e:
            print(f"Audio generation error: {e}")
            return ""
